import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/painting.dart';
import 'package:golden_test/src/config.dart';

/// PNG bytes returned for every network image request during golden tests.
///
/// Defaults to a 2048×2048 squared frame with a corner-to-corner X — the
/// classic [Placeholder]-style "missing image" mark — rendered at high
/// resolution so it stays crisp at any devicePixelRatio. The diagonals cross
/// at dead center, so even a tight `BoxFit.cover` crop (e.g. a small circular
/// avatar) always lands on visible content. Drawn with a transparent fill and
/// a white-halo + dark-stroke double outline, so it stays legible over both
/// light and dark app backgrounds without needing separate assets.
/// Override in `flutter_test_config.dart` to supply custom bytes, e.g.:
/// ```dart
/// goldenTestNetworkImageStubPng = myPlaceholderPngBytes;
/// ```
Uint8List goldenTestNetworkImageStubPng = base64Decode(
  'iVBORw0KGgoAAAANSUhEUgAACAAAAAgABAMAAABAic4DAAAAHlBMVEUAAAD///83QVEA'
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAB7Q/lAAAACHRSTlMA6/8AAAAAAFKEC4AAADMpSURB'
  'VHja7d1pcuRIgiVhkicg4wQk73/IriVraZHMCgcchC366e8ZERczgz6dns7gywsAAAAA'
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABm5dURAN3P7ePd'
  'rQDVz+3148OtANXP7eNDAgDVz+1vRpIAQPVz+/sPkgBA83P7h5EkAND83P75gyQAUPzc'
  '/jCSBACKn9u/fpAEAHqf27+NJAGA3uf2nx8kAYDa5/b2X79IAgB3BcDHryl+0feXBADu'
  'D4CP788ZAuD7WwIAAwLg+3uGAPiWAMCIAPieIAH+FgASABgSABMkwN9/hAQARgTA+AT4'
  'RwBIAGBIAAxPgH/+CAkAjAiA0QnwRwBIAGBIAAxOgH/9CAkAjAiAsQnw7wCQAMCQABia'
  'AP/5Ef8vAf7rxwG4iD8NgJEJ8PbArwNwCX+5sTMEgAQAhgTAuAR4e/D3Afi5ABiWAI//'
  'QAA/FQCjEuDtwC8E8FMBMCgBjv1EAD8TAGMS4O3gbwTwMwEwJAGO/0gAPxEAIxLg7cSv'
  'BPATATAgAc79TADXB8D9CfB28ncCuD4Abk+Aj28JAMwSAN9f7zf/d0m/JAAwTQDc/N/g'
  '/rWIJABwfwDc+89wvP4vE0kA4PYAuDUB/reKJABwdwDcmQCvv3ORBABuDoAbE+D3MpIA'
  'wL0BcF8CvD5iIwkA3BoAtyXAYzqSAMCdAXBXArw+6iMJANwYADclwONCkgDAfQFwTwK8'
  'HjGSBABuC4B7EuBDAgAzBsA9/0MACQB0A0ACAOEAkABAOQAkABAOAAkAlANAAgDhAJAA'
  'QDkAjiYAgOeYKgAOJwCAZ5gsACQAEA4ACQCUA0ACAOEAkABAOQAkABAOAAkAlANAAgDh'
  'AJAAQDkAJAAQDgAJAJQDQAIA4QCQAEA5ACQAEA6Al5cvCQAMDoDPcQL4lgDA2AD4NVIA'
  'EgAYGwDfIwUgAYCxATBWABIAGBoAYwUgAYChATBYABIAGBkAgwUgAYCRATBaABIAGBgA'
  'owUgAYCBATBcABIAGBcAwwUgAYBxATBeABIAGBYA4wUgAYBhATCBACQAMCoAJhCABABG'
  'BcAMApAAwKAAmEEAEgAYFABTCOBrlX/EDJiV13MBMIUAvpf5V8yASTkZAHMIQAIAQwJg'
  'DgFIAGBIAEwiAAkAjAiASQQgAYARATCLACQAMCAAZhGABAAGBMA0ApAAwP0BMI0AJABw'
  'fwDMIwAJANweAPMIQAIAtwfARAKQAMDdATCRACQAcHcAzCoACQD8RAAsIgAJAPxAACwj'
  'AAkAXB8AywhAAgDXB8A6ApAAwOUBsI4AJABweQAsJAAJAFwdAAsJQAIAVwfASgKQAMDF'
  'AbCSACQAcHEALCUACQBcGwBLCUACANcGwFoCkADApQGwlgAkAHBpACwmAAkAXBkAiwlA'
  'AgBXBsBqApAAwIUBsJoAJABwYQAsJwAJAFwXAMsJQAIA1wXAegKQAMBlAbCeACQAcFkA'
  'LCgACQBcFQALCkACAFcFwIoCkADARQGwogAkAHBRACwpAAkAXBMASwpAAgDXBMCaApAA'
  'wCUBsKYAJABwSQAsKgAJAFwRAIsKQAIAVwTAqgKQAMAFAbCSAN4lAPBcALyvLIBXCQA8'
  'FQAvKwvgRQIATwXA2gKQAMBTAbC2ACQA8FQALC4ACQA8EwCLC0ACAM8EwOoCkADAEwGw'
  'ugAkAPBEACwvAAkAnA+A5QUgAYDzAbC+ACQAcP5TWF4AEgA4/yWsLwAJAJz+ENYXgAQA'
  'Tn8HGwhAAgBnP4MNBCABgLNfwQ4CkAAQACc/gh0EIAEgAE5+A1sIQAJAAJz7BLYQgASA'
  'ADj3BewhAAkAAXDqA9hDABIAAuDU+99EABIAAuDM899EABIAAuDM699FABIAAuDE499F'
  'ABIAAuDE299GABIAAuD4099GABIAAuD4y99HABIAAuDww99HABIAAuDwu99IABIAAuDo'
  's99IABIAAuDoq99JABIAAuDgo99JABIAAuDgm99KABIAAuDYk99KABIAAuDYi99LABIA'
  'AuDQg99LABIAAuDQe99MABIAAuDIc99MABIAAuDIa99NABIAAuDAY99NABIAAuDAW99O'
  'ABIAAuDxp76dACQABMDjL30/AUgACICHH/p+ApAAEAAPv/MNBSABIAAefeYbCkACQAA8'
  '+sp3FIAEgAB48JHvKAAJAAHw4BvfUgASAALgsSe+pQAkAATA8U9lHwFIAAiAhx74ngKQ'
  'ABAAh7+UjQQgASAAHnnemwpAAkAAHP1QdhKABIAAeOBx7yoACQABcPA72UoAEgAC4PdP'
  'e1sBSAAIgGOfyV4CkAAQAL992PsKQAJAABz6SjYTgASAAHjpCkACQACUBSABIADCApAA'
  'EABlAUgACICwACQABEBZABIAAiAsAAkAAVAWgASAAAgLQAJAAJQFIAEgAMICkAAQAGUB'
  'SAAIgLAAJAAEQFkAEgACICwACQABUBaABIAACAtAAkAAlAUgASAAwgKQABAAZQFIAAiA'
  'sAAkAARAWQASAAIgLAAJAAFQFoAEgAAIC0ACQACUBSABIADCApAAEABlAUgACICwACQA'
  'BEBZABIAAiAsAAkAAVAWgASAAAgLQAJAAJQFIAEgAMICkAAQAGUBSAAIgLAAJAAEQFkA'
  'EgACICwACQABUBaABIAACAtAAkAAlAUgASAAwgKQABAAZQFIAAiAsAAkAARAWQASAAIg'
  'LAAJAAFQFoAEgAAIC0ACQACUBSABIADCApAAEABlAUgACICwACQABEBZABIAAiAsAAkA'
  'AVAWgASAAAgLQAJAAJQFIAEgAMICkAAQAGUBSAAIgLAAJAAEQFkAEgACICwACQABUBaA'
  'BEA+AMoCkADIB0BaABIA9QBIC0ACoB4AbQFIAMQDoC0ACYB4AMQFIAHQDoC4ACQA2gFQ'
  'F4AEQDoA6gKQAEgHQF4AEgDlAMgLQAKgHAAEIAEQDgACkAAIBwABSACEA4AAJADCAUAA'
  'EgDhACAACYBwABCABEA4AAhAAiAcAAQgARAOAAKQAAgHAAFIAIQDgAAkAMIBQAASAOEA'
  'IAAJgHAAEIAEQDgACEACIBwABCABEA4AApAACAcAAUgAhAOAACQAwgFAABIA4QAgAAmA'
  'cAAQgARAOAAIQAIgHAAEIAEQDgACkAAIBwABSACEA4AAJADCAUAAEgDhACAACYBwABCA'
  'BEA4AAhAAiAcAAQgARAOAAKQAAgHAAFIAIQDgAAkAMIBQAASAOEAIAAJgHAAEIAEQDgA'
  'CEACIBwABCABEA4AApAACAcAAUgAhAOAACQAwgFAABIA4QAgAAmAcAAQgARAOAAIQAIg'
  'HAAEIAEQDgACkAAIBwABSACEA4AAJADCAUAAEgDhACAACYBwABCABEA4AAhAAiAcAAQg'
  'ARAOAAKQAAgHAAFIAIQDgAAkAMIBQAASAOEAIAAJgHAAEIAEQDgACEACIBwABCABEA4A'
  'ApAACAcAAUgAlB8SAUgAhN8RAUgAhJ8RAUgAhF8RAUgAhB8RAUgAhN8QAUgAhJ8QAUgA'
  'hF8QAUgAhB8QAUgAhN8PAUgAhJ8PAUgAhF8PAUgAhB8PAUgAhN8OAUgAhJ8OAUgAhF8O'
  'AUgAhB8OAUgAhN8NAUgAhJ8NAUgAhF8NAUgAhB8NAUgAhN8MAUgAhJ8MAUgAhF8MAUgA'
  'hB8MAUgAhN8LAUgAhJ8LAUgAhF8LAUgAhB8LAUgAhN8KAUgAhJ8KAUgAhF8KAUgAhB8K'
  'AUgAhN8JAUgAhJ8JAUgAhF8JAUgAhB8JAUgAhN8IAUgAhJ8IAUgAhF8IAUgAhB8IAUgA'
  'hN8HAUgAhJ8HAUgAhF8HAUgAhB8HAUgAhN8GAUgAhJ8GAUgAhF8GAUgAhB8GAUgAhN8F'
  'AUgAhJ8FAUgAhF8FAUgAhB8FAUgAhN8EAUgAhJ8EAUgAhF8EAUgAhB8EAUgAhN8DAUgA'
  'hJ8DAUgAhF8DAUgAhB8DAUgAhN8CAUgAhJ8CAUgAhF8CAUgAhB8CAUgAhN8BAUgAhJ8B'
  'AUgAhF8BAUgAhB8BAUgAhN8AAUgAhJ8AAUgAhF8AAUgAhB8AAUgAhO+fACQAwtdPABIA'
  '4dsnAAmA8OUTgBFA+O4JwAogfPUEYAYQvnkCsAMIXzwBGAKE750ALAHC104ApgDhWycA'
  'W4DwpROAMUD4zgnAGiB85QRgDhC+cQKwBwhfOAEYBITvmwAsAsLXTQAmAeHbJgCbgPBl'
  'E4BRQPiuCcAqIHzVBGAWEL5pArALCF80ARgGhO+ZACwDwtdMAKYB4VsmANuA8CUTgHFA'
  '+I4JwDogfMUEYB4QvmECsA8IXzABGAiE75cALATC10sAJgLh2yUAG4Hw5RKAkUD4bgnA'
  'SiB8tQRgJhC+WQKwEwhfLAEYCoTvlQAsBcLXSgCmAuFbJQBbgfClEoCxQPhOCcBaIHyl'
  'BGAuEL5RArAXCF8oARgMhO+TACwGwtdJACYD4dskAJuB8GUSgNFA+C4JwGogfJUEYDYQ'
  'vkkCsBsIXyQBGA6E75EALAfC10gApgPhWyQA24HwJRKA8UD4DgnAeiB8hQRgPhC+QQKw'
  'HwhfIAEYEITvjwAsCMLXRwAmBOHbIwAbgvDlEYARQfjuCMCKIHx1BGBGEL45ArAjCF8c'
  'ARgShO+NACwJwtdGAKYE4VsjAFuC8KURgDFB+M4IwJogfGUEYE4QvjECsCcIXxgBGBSE'
  '74sALArC10UAJgXh2yIAm4LwZRGAUUH4rgjAqiB8VQRgVhC+KQKwKwhfFAEYFoTviQAs'
  'C8LXRACmBeFbIgDbgvAlEYBxQfiOCMC6IHxFBGBeEL4hArAvCF8QARgYhO+HACwMwtdD'
  'ACYG4dshABuD8OUQgJFB+G4IwMogfDUEYGYQvhkCsDMIXwwBGBqE74UALA3C10IApgbh'
  'WyEAW4PwpRCAsUH4TgjA2iB8JQRgbhC+EQKwNwhfCAEYHITvgwAsDsLXQQAmB+HbIACb'
  'g/BlEIDRQfguCMDqIHwVBGB2EL4JArA7CF8EARgehO+BACwPwtdAAKYH4VsgANuD8CUQ'
  'gPFB+A4IwPogfAUEYH4QvgECsD8IXwABGCCEz58ALBDCx08AJgjh0ycAGyQAwodPAEZI'
  'AITPngCskAAIHz0BmCEBED55ArBDAiB88ARgiARA+NwJwBIJgPCxE4ApEgDhUycAWyQA'
  'wodOAMZIAITPnACskQAIHzkBmCMBED5xArBHAiB84ARgkARA+LwJwCIJgPBxE4BJEgDh'
  '0yYAmyQAwodNAEZJAITPmgCskgAIHzUBmCUBED5pArBLAiB80ARgmARA+JwJwDIJgPAx'
  'E4BpEgDhUyYA2yQAwodMAMZJAITPmACskwAIHzEBmCcBED5hArBPAiB8wARgoARA+HwJ'
  'wEIJgPDxEoCJEgDh0yUAGyUAwodLAEZKAITPlgCslAAIHy0BmCkBED5ZArBTAiB8sARg'
  'qARA+FwJwFIJgPCxEoCpEgDhUyUAWyUAwodKAMZKAITPlACslQAIHykBmCsBED5RArBX'
  'AiB8oARgsARA+DwJwGIJgPBxEoDJEgDh0yQAmyUAwodJAEZLAITPkgCslgAIHyUBmC0B'
  'ED5JArBbAiB8kARguJxj+BwJwHI5xvAxEoDpcorhUyQA2+UQw4dIAMbLGYbPkACslyMM'
  'HyEBmC8nGD5BArBfDjB8gARgwJxf+PwIwII5vvDxEYAJc3rh0yMAG+bwwodHAEbM2YXP'
  'jgCsmKMLHx0BmDEn9+VZEYAdc3DBgyMAQ+bcvCoCsGSOrXhsBGDKnJpHRQC2zKEVD40A'
  'jJkz86YIwJo5suKREYA5c2KeFAHYMwf28UIABGDQnBcBEIBFc1wEQAAmzWkRAAHYNIdF'
  'AARg1JwVARCAVXNUBEAAZs1JEQAB2DUHRQAEYNicEwEQgGVzTARAAKbNKREAAdg2h0QA'
  'BGDcnBEBEIB1c0QEQADmzQkRAAHYNwdEAARg4JwPARCAhXM8BEAAJs7pEAAB2DiHQwAE'
  'YOScDQEQgJVzNARAAGbOyRCAm7NzDoYACMDQORcCkACWzrEQgLszdU6FACSArXMoBCAB'
  'wmPnTAhAAnTXzpEQgAQIz50TIQAJ0N07B0IAEiA8eM6DACRAd/EcBwFIgPDkOQ0CkADd'
  'zXMYBCABwqPnLAhAAnRXz1EQgAQIz56TIAAJ0N09B0EAEiA8fM6BACRAd/kcAwG4w/D0'
  'OQUCkADd7XMIBOASw+PnDAhAAnTXzxEQgFsMz58TIAAJ0N0/AUAArjE8gAKAACRAdwEF'
  'AAG4x/AECgACkADdDRQABOAiwyMoAAhAAnRXUAAQAMIzKAAIAN0dFAAEgPAQCgACQHcJ'
  'BQABIDyFAoAA0N1CAUAACI+hACAAdNdQABAAwnMoAAgA3T0UAASA8CAKAAJAdxEFAAEg'
  'PIkCgADQ3UQBQAAIj6IAIAB0V1EAEADCsygACADdXRQABIDwMAoAAkB3GQUAASA8jQKA'
  'ANDdRgFAAG4vPI4CgADcXncdBQABEEB4HgUAAbjV7j4KAAIggPBACgACcK3dhRQABEAA'
  '4YkUAATgXrsbKQAIgADCIykACMDFdldSABAAAYRnUgAQgJvt7qQAIAACCA+lACAAV9td'
  'SgFAAAQQnkoBQADutruVAoAACCA8lgKAAFxudy0FAAEQQHguBQABuN3uXgoAAiCA8GAK'
  'AAJwvd3FFAAEQADhyRQABOB+u5spAAiAAMKjKQAIwAV3V1MAEAABhGdTABAAAXR3UwAQ'
  'AAGEh1MAEAABdJdTABAAAYSnUwAQAAF0t1MAEAABhMdTABAAAXTXUwAQAAGE51MAEAAB'
  'dPdTABAAAYQHVAAQAAF0F1QAEAABhCdUABAAAXQ3VAAQAAGER1QAEAABdFdUABAAAYRn'
  'VAAQAAF0d1QAEAABhIdUABAAAXSXVAAQAAGEp1QAEAABdLdUABAAAYTHVAAQAAF011QA'
  'EAABhOdUABAAAXT3VAAQAAGEB1UAEAABdBdVABAAAYQnVQAQAAF0N1UAEAABhEdVABAA'
  'AXRXVQAQAAGEZ1UAEAABdHdVABAAAYSHVQAQAAF0l1UAEAABhKdVABAAAXS3VQAQAAGE'
  'x1UAEAABdNdVABAAAYTnVQAQAAF091UAEAABhAdWABAAAXQXVgAQAAGEJ1YAEAABdDdW'
  'ABAAAYRHVgAQAAF0V1YAEAABhGdWABAAAXR3VgAQAAGEh1YAEAABdJdWABAAAYSnVgAQ'
  'AAF0t1YAEAABhMdWABAAAXQTQAAQAAGEE0AAEAABdBNAABAAAYQTQAAQAAF0E0AAEAAB'
  'hBNAABAAAXQTQAAQAAGEE0AAEAABdBNAABAAAYQTQAAQAAF0E0AAEAABhBNAABAAAXQT'
  'QAAQAAGEE0AAEAABdBNAABAAAYQTQAAQAAF0E0AAEAABhBNAABAAAXQTQAAQAAGEE0AA'
  'EAABdBNAABAAAYQTQAAQAAF0E0AAEAABhBNAABAAAXQTQAAQAAGEE0AAEAABdBNAABAA'
  'AYQTQAAQAAF0E0AAEAABhBNAABAAAXQTQAAQAAGEE0AAEAABdBNAABAAAYQTQAAQAAF0'
  'E0AAEAABhBNAABAAAXQTQAAQAAGEE0AAEAABdBNAABAAAYQTQAAQAAF0E0AAEAABhBNA'
  'ABAAAXQTQAAQAAGEE0AAEAABdBNAABAAAYQTQAAQAAF0E0AAEAABhBNAABAAAXQTQAAQ'
  'AAGEE0AAEAABdBNAABAAAYQTQAAQAAF0E0AAEAABhBNAABAAAXQTQAAQAAGEE0AAEAAB'
  'dBNAABAAAYQTQAAQAAF0E0AAEAABhBNAABAAAXQTQAAQAAGEE0AAEAABdBNAABAAAYQT'
  'QAAQAAF0E0AAEAABhBNAABAAAXQTQAAQAAGEE0AAEAABdBNAABAAAYQTQAAQAAF0E0AA'
  'EAABhBNAABAAAXQTQAAQAAGEE0AAEAABdBNAABAAAYQTQAAQAAF0E0AAEAABhBNAABAA'
  'AXQTQAAQAAGEE0AAEAABdBNAABAAAYQTQAAQAAF0E0AAEAABhBNAABAAAXQTQAAQAAGE'
  'E0AAEAABdBNAABAAAYQTQAAQAAF0E0AAEAABhBNAABAAAXQTQAAQAAGEE0AAEAABdBNA'
  'ABAAAYQTQAAQAAF0E0AAEAABhBNAABAAAXQTQAAQAAGEE0AAEAABdBNAABAAAYQTQAAQ'
  'AAF0E0AAEAABhBNAABAAAZQTQAAQAAFIAAFAAASQTgABQAAEEE4AAUAABNBNAAFAAAQQ'
  'TgABQAAE0E0AAUAABBBOAAFAAATQTQABQAAEEE4AAUAABNBNAAFAAAQQSwABQAAE0E2A'
  'LwFAAATQTQABQAAE0E0AAUAABBBOAAFAAATQTQABQAAEEE4AAUAABNBNAAFAAAQQTgAB'
  'QAAE0E0AAUAABBBOAAFAAATQTQABQAAEEE4AAUAABNBNAAFAAAQQTgABQAAE0E0AAUAA'
  'BBBOAAFAAATQTQABQAAEEE4AAUAABNBNAAFAAAQQTgABQAAE0E0AAUAABBB/QAKAAAgg'
  'mgACgAAIQAIIAAIggHYCCAACIIBwAggAAiCAbgIIAAIggHACCAACIIBuAggAAiCA8CMS'
  'AARAAN0EEAAEQADhVyQACIAAugkgAAiAAPzrgAKAAAjAHwr809tzYgRAANkAcHUEQADl'
  'AJAABEAA4QBwdwRAAOUAkAAEQADhAHB5BEAA5QCQAARAAOEAcHsEQADlAJAABEAA4QBw'
  'fQRAAOUAkAAEQADhAHB/BEAAuQDw3wQSAAF0A+CX/yiQAAggHAD+WQACIIBwAPh3AQiA'
  'AMoBIAEIgADCASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADC'
  'ASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAAygEg'
  'AQiAAMIBIAEIgADKASABCIAAwgEgAQiAACIB8MD/EWdKAASw7d8C+JYABEAA3T8GJAEI'
  'gADKfwxIAhAAAYT/GqAEIAACKP81QAlAAAQQ/nPAEoAACKD854AlAAEQQDYAJAABEEA5'
  'ACQAARBAOAAkAAEQQDkAJAABEEAuAF4lAAEQQDYA3l8kAAEQQDYATvxfAAEQwDYB8CIB'
  'CIAAugEgAQiAAMoBIAEIgADCASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiA'
  'AMoBIAEIgADCASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADC'
  'ASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAAygEg'
  'AQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAAygEgAQiAAMIBIAEI'
  'gADKASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAAygEgAQiAAMIBIAEIgADKASABCIAA'
  'wgEgAQiAAMoBIAEIgADCASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoB'
  'IAEIgADCASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADCASAB'
  'CIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAAygEgAQiA'
  'AMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAAygEgAQiAAMIBIAEIgADK'
  'ASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEg'
  'AQiAAMoBIAEIgADCASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEI'
  'gADCASABCIAAygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAA'
  'ygEgAQiAAMIBIAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAAygEgAQiAAMIB'
  'IAEIgADKASABCIAAwgEgAQiAAMoBIAEIgADCASABCIAAygEgAQiAANJbKwEIgADKUysB'
  'CIAAwksrAQiAAMpDKwEIgADCOysBCIAAyjMrAQiAAMIrKwEIgADKIysBCIAAwhsrAQiA'
  'AMoTKwEIgADCCysBCIAAygMrAQiAAML7KgEIgADK8yoBCIAAwusqAQiAAMrjKgEIgADC'
  '2yoBCIAAytMqAQiAAMLLKgEIgADKwyoBCIAAwrsqAQiAAMqzKgEIgADCqyoBCIAAyqMq'
  'AQiAAMKbKgEIgADKkyoBCIAAwosqAQiAAMqDKgEIgADCeyoBCIAAynMqAQiAAMJrKgEI'
  'gADKYyoBCIAAwlsqAQiAAMpTKgEIgADCSyoBCIAAykMqAQiAAMI7KgEIgADKMyoBCIAA'
  'wisqAQiAAMojKgEIgADCGyoBCIAAyhMqAQiAAMILKgEIgADKAyoBCIAAwvspAQiAAMrz'
  'KQEIgADC6ykBCIAAyuMpAQiAAMLbKQEIgADK0ykBCIAAwsspAQiAAMrDKQEIgADCuykB'
  'CIAAyrMpAQjABYdXUwIQAAGUR1MCEID7DW+mBCAAAihPpgQgANcbXkwJQAAEUB5MCUAA'
  'bje8lxKAAAigPJcSgABcbngtJQABEEB5LCUAAbjb8FZKAAIggPJUSgACcLXhpZQABEAA'
  '5aGUAATgZsM7KQEIgADKMykBCMDFhldSAhAAAZRHUgIQgHsNb6QEIAACKE+kBCAA1xpe'
  'SAlAAARQHkgJQABuNbyPEoAACKA8jxKAANxeeB0lAAG4vfI4SgACQHgbJQABoDyNEoAA'
  'EF5GCUAAKA+jBCAAhHdRAhAAyrMoAQgA4VWUAASA8ihKAAJAeBMlAAGgPIkSgAAQXkQJ'
  'QAAoD6IEIACE91ACEADKcygBCADhNZQABIDyGEoAAkB4CyUAAaA8hRKAABBeQglAACgP'
  'oQQgAIR3UAIQAMozKAEIQACEV1ACEIB7LI+gBCAAARDeQAlAAK6xPIESgAAEQHgBJQAB'
  'uMXyADoBAhAA4f1zBATgEsvz5wwIQACE188hEIA7LI+fUyAAARDePsdAAK6wPH3OgQAE'
  'QHj5HAQBCIDy8DkJAhAA4d1zFAQgAMqz5ywIQACEV89hEIAAKI+e0yAAARDePMdBAAKg'
  'PHnOgwAEQHjxHAgBCIDy4DkRAhAA4b1zJAQgAMpz50wIQACE186hEIAAKI+dUyEAWxfe'
  'OsdCAKauPHXOhQAsXXjpHAwBGLry0DkZArBz4Z1zNARg5soz52wIwMqFV87hEICRK4+c'
  '0yEAGxfeOMdDACaufFLOhwAsXHjhHBABGLjyQTkhArBv4X1zRARg3srn5IwIwLqF180h'
  'EYBxKx+TUyIA2xbeNsdEAKbN/+vWORGAZXNQDooADJuTclIEYNcclaMiALPmrJwVAVg1'
  'h5U+LAIwak7LgyIAm+a4CIAATJrzIgACsGgOjAAIwKA5MQIgAHvmyAiAAMyZMyMAArBm'
  'Do0ACMCYOTUCIABb5tgIgABMmXMjAAKwZA6OAAjAkDk5AiAAO+boCIAAzJizIwACsGIO'
  'jwAIwIg5PQIgABvm+AiAAEyY8yMAArBgDpAACMCAOUECIAD75QgJgADMlzMkAAKwXg6R'
  'AMoCMF5OkQC6ArBdjpEAwgIwXc6RALoCsFwOkgDCAjBcTpIAugKwW46SAMICMFvOkgC6'
  'ArBaDpMAwgIwWk6TALoCsFmOkwDCAjBZzpMAugKwWA6UAMICMFhOlAC6ArBXjpQAwgIw'
  'V86UALoCsFYOlQDCAjBWTpUAugKwVY6VAMICMFXOlQC6ArBUDpYAwgIwVE6WALoCsFOO'
  'lgDCAjBTzpYAugKwUg6XAMICMFJOlwC6ArBRjpcAwgIwUc6XALoCsFAOmADCAjBQTpgA'
  'ugKwT46YAMICME/OmAC6ArBODpkAwgIwTk6ZALoCsE2OmQDCAjBNzpkAugKwTA6aAMIC'
  'MExOmgC6ArBLjpoAwgIwS86aALoCsEoOmwDCAjBKTpsAugKwSY6bAMICMEnOmwC6ArBI'
  'DpwAwgIwSE6cALoCsEeOnADCAhAAzpwAugIQAA6dAMICEABOnQC6AhAAjp0AwgIQAM6d'
  'ALoCEAAOngDCAhAATp4AugIQAI6eAMICEADOngC6AhAADp8AwgIQAE6fALoCEACOnwDC'
  'AhAAzp8AugIQAC6AAMICEABugAC6AhAAroAAwgIQAO6AALoCEAAugQDCAhAAboEAugIQ'
  'AK6BAMICEADugQC6AhAALoIAwgIQAG6CALoCEACuggDCAhAA7oIAugIQAC6DAMICEABu'
  'gwC6AhAAroMAwgIQAO6DALoCEAAuhADCAhAAboQAugIQAK6EAMICEADuhAC6AhAALoUA'
  'wgIQAG6FALoCEACuhQDCAhAA7oUAugIQAC6GAMICEABuhgC6AhAAroYAwgIQAO6GALoC'
  'EAAuhwDCAhAAbocAugIQAK6HAMICEADuhwC6AhAALogAwgIQAG6IALoCEACuiADCAhAA'
  '7ogAugIQAC6JAMICEABuiQC6AhAArokAwgIQAO6JALoCEAAuigDCAhAAbooAugIQAK6K'
  'AMICEADuigC6AhAALosAwgIQAG6LALoCEACuiwDCAhAA7osAugIQAC6MAMICEABujAC6'
  'AhAArowAwgIQABKAALoCEAASgADCAhAAEoAAugIQABKAAMICEAASgAC6AhAAEoAAwgIQ'
  'ABKAALoCEAASgADCAhAAEoAAugIQABKAAMICEAASgAC6AhAAEoAAwgIQABKAALoCEAAS'
  'gADCAhAAEoAAugIQABKAAMICEAASgAC6AhAAEoAAwgIQABKAALoCEAASgADCAhAAEoAA'
  'ugIQABKAAMICEAASgAC6AhAAEoAAwgIQABKAALoCEAASgADCAhAAEoAAugIQABKAAMIC'
  'EAASgAC6AhAAEoAAwgIQABKAALoCEAASgADCAhAAEoAAugIQABKAAMICEAAS4J0AsgIQ'
  'ABJg/mslAFOB8L0SgKVA+GIJwFAgfLMEYCcQvloCMBMI3y0BWAmEL5cAjATCt0sANgLh'
  '6yUAE4Hw/RKAhUD4ggnAQCB8wwRgHxC+YgIwDwjfMQFYB4QvmQCMA8K3TAC2AeFrJgDT'
  'gPA9E4BlQPiiCcAwIHzTBGAXEL5qAjALCN81AVgFhC+bAIwCwrdNADYB4esmAJOA8H0T'
  'gEVA+MIJwCAgfOMEYA8QvnICMAcI3zkBWAOEL50AjAHCt04AtgDhaycAU4DwvROAJUD4'
  '4gnAECB88wRgBxC+egIwAwjfPQFYAYQvnwCMAMK3TwACAOHrJwABgPD9E4AAQPgBEIAA'
  'QPgFEIAAQPgJEIAAQPgNEIAAQPgREIAAQPgVEIAAQPgZEIAAQPgdEIAAQPghEIAAQPgl'
  'EIAAQPgpEIAAQPgtEIAAQPgxEIAAQPg1EIAAQPg5EIAAQPg9EIAAQPhBEIAAQPhFEIAA'
  'QPhJEIAAQPhNEIAAQPhREIAAQPhVEIAAQPhZEIAAQPhdEIAAQPhhEIAAQPhlEIAAQPhp'
  'EIAAQPhtEIAAQPhxEIAAQPh1EIAAQPh5EIAAQPh9EIAAQPiBEIAAQPiFEIAAQPiJEIAA'
  'QPiNEIAAQPiREIAAQPiVEIAAQPiZEIAAQPidEIAAQPihEIAAQPilEIAAQPipEIAAQPit'
  'EIAAQPixEIAAQPi1EIAAQPi5EIAAQPi9EIAAQPjBEIAAQPjFEIAAQPjJEIAAQPjNEIAA'
  'QPjREIAAQPjVEIAAQPjZEIAAQPjdEIAAQPjhEIAAQPjlEIAAQPjpEIAAQPjtEIAAQPjx'
  'EIAAQPj1EIAAQPj5EIAAQPj9EIAAQPgBEYAAQPgFEYAAQPgJEYAAQPgNEYAAQPgREYAA'
  'QPgVEYAAQPgZEYAAQPgdEYAAQPghEYAAQPglEYAAQDgBCEAAIJwABCAAEE4AAhAACCcA'
  'AQgAhBOAAAQAwglAAAIA4QQgAAGAcAIQgABAOAEIQAAgnAAEIAAQTgACEAAIJwABCACE'
  'E4AABADCCUAAAgDhBCAAAYBwAhCAAEA4AQhAACCcAAQgABBOAAIQAAgnAAEIAIQTgAAE'
  'AMIJQAACAOEEIAABgHACEIAAQDgBCEAAIJwABCAAEE4AAhAACCcAAQgAhBOAAAQAwglA'
  'AAIA4QQgAAGAcAIQgABAOAEIQAAgnAAEIAAQTgACEAAIJwABCACEE4AABADCCUAAAgDh'
  'BCAAAYBwAhCAAEA4AQhAACCcAAQgABBOAAIQAAgnAAEIAIQTgAAEAMIJQAACAOEEIAAB'
  'gHACEIAAQDgBCEAAIJwABCAAEE4AAhAACCcAAQgAhBOAAAQAwglAAAIA4QQgAAGAcAIQ'
  'gABAOAEIQAAgnAAEIAAQTgACEAAIJwABCACEE4AABADCCUAAAgDhBCAAAYBwAuQFIABQ'
  'ToC8AAQAyglQF4AAQDoB6gIQAEgnQFwAAgDtBIgLQACgnQBtAQgAxBOgLQABgHgCpAUg'
  'AFBPgLQABADqCVAWgABAPgHKAhAAyCdAWAACABIgLAABAAnQFYAAgAQIC0AAQAJ0BSAA'
  'IAHCAhAAkABdAQgASICwAAQAJEBXAAIAEiAsAAEACdAVgACABAgLQABAAnQFIAAgAcIC'
  'EACQAF0BCABIgLAABAAkQFcAAgASICwAAQAJ0BWAAIAECAtAAEACdAUgACABwgIQAJAA'
  'XQEIAEiAsAAEACRAVwACABIgLAABAAnQFYAAgAQIC0AAQAJ0BSAAIAHCAhAAkABdAQgA'
  'SICwAAQAJEBXAAIAEiAsAAEACdAVgACABAgLQABAAnQFIAAgAcICEACQAF0BCABIgLAA'
  'BAAkQFcAAgASICwAAQAJ0BWAAIAECAtAAEACdAUgACABwgIQAJAAXQEIAEiAsAAEACRA'
  'VwACABIgLAABAAnQFYAAgAQIC0AAQAJ0BSAAIAHCAhAAkABdAQgASICwAAQAJEBXAAIA'
  'EiAsAAEACdAVgACABAgLQABAAnQFIAAgAcICEACQAF0BCABIgLAABAAkQFcAAgASICwA'
  'AQAJ8J4VgACABPjtw95XAAIAEuDQZ7KVAAQAJMDvn/a2AhAAkADHvpOdBCAAIAEeeNy7'
  'CkAAQAIc/FA2EoAAgAR45HlvKgABAAlw9EvZRwACABLgoQe+pwAEACTA4U9lGwEIAEiA'
  'x574lgIQAJAAX4e/lV0EIAAgAR585DsKQABAAjz4yjcUgACABHj0mW8oAAEACfDoO99P'
  'AAIAEuDhh76fAAQAJMDDL307AQgASIDHn/p2AhAAkACPv/XdBCAAIAEOPPbdBCAAIAEO'
  'vPbNBCAAIAGOPPfNBCAAIAGOvPe9BCAAIAEOPfi9BCAAIAEOvfitBCAAIAGOPfmtBCAA'
  'IAGOvfmdBCAAIAEOPvqdBCAAIAEOvvqNBCAAIAGOPvuNBCAAIAGOvvt9BCAAIAEOP/x9'
  'BCAAIAEOv/xtBCAAIAGOP/1tBCAAIAGOv/1dBCAAIAFOPP5dBCAAIAFOvP5NBCAAIAHO'
  'PP9NBCAAIAHOvP89BCAAIAFOfQB7CEAAQAKc+gK2EIAAgAQ49wlsIQABAAlw7hvYQQAC'
  'ABLg5EewgwAEAHDyK9hAAAIAOPsZbCAAAQCc/Q7WF4AAAE5/COsLQAAAp7+E5QUgAIDz'
  'n8LyAhAAwPkEWF0AAgB4IgFWF4AAAJ5IgMUFIACAZxJgcQEIAOCZBFhbAAIAeCoB1haA'
  'AACeSoClBSAAgOcSYGkBCADguQRYWQACAHgyAVYWgAAAnkyAhQXwIQCAJxNgEwEIAOBM'
  'AuwhAAEAXJIAawpAAACXJMCSAhAAwDUJsKQABABwTQKsKAABAFyUACsKQAAAFyXAggIQ'
  'AMBVCbCgAAQAcFUCrCcAAQBclgDrCUAAAJclwHICEADAdQmwnAAEAHBdAqwmAAEAXJgA'
  'qwlAAAAXJsBiAhAAwJUJsJgABABwZQKsJQABAFyaAGsJQAAAlybAUgIQAMC1CbCUAAQA'
  'cG0CrCQAAQBcnAArCUAAABcnwEICEADA1QmwkAAEAHB1AqwjAAEAXJ4A6whAAACXJ8Ay'
  'AhAAwPUJsIwABABwfQKsIgABAPxAAqwiAAEA/EACLCIAAQD8RAIsIgABAPxEAswrgC8B'
  'APx4AkwrAAEA3J4A0whAAAD3J8A0AhAAwP0JMIsABAAwIAFmEYAAAAYkwCQCEADAiASY'
  'RAACABiRAHMIQAAAQxJgDgEIAGBIAkwhAAEAjEmAKQQgAIAxCTCDAAQAMCgBZhDAyb90'
  'DuDj3B/V/jWRAL7O/aFzAH/OgQSYQAACABiVAOMFIACAYQkwXgACABiWAMMFIACAcQkw'
  'XAACABiXAKMFIACAgQkwWgACABiYAIMFIACAkQkwWAACABiZAGMFIACAoQkwVgACABia'
  'AEMFIACAsQkwVAACABibACMFIACAwQkwUgACABicAAMFIACA0Qnwucq/Ygbg+gR4X+Uf'
  'MQPwAwkgAAAJIAAACSAAAAkgAAAJIAAACSAAAAkgAAAJIAAACSAAAAkgAAAJIAAACSAA'
  'AAkgAAAJcE0AfAM4zNe0CXDu75gDOMKsCSAAgHACCACgmwACAAgngAAAugkgAIBwAggA'
  'oJsAAgAoJ4AAAOZMgPd7/2cAAgCYKQFu/v8FEADARAnwfu//HoAAAGZKgJv/NwEFADBR'
  'Arzf+98CCABgpgS4+b8GFADARAnwfu+/ByAAgJkS4OZ/EUgAABMlwPu9/yagAABmSoCb'
  '/1VgAQBMlAA3/2GANwEATJQAd/9lIAEAzJMAn3cL4E0AANMkwP1/HVgAALMkwOf9AngT'
  'AMAkCfDyMkECCABgSAJ8jhDAmwAApkiAl5cJEkAAAEMS4HOMAN4EADBBAry8TJAAAgAY'
  'kgCfowTwJgCA4Qnw8jJBAggAYEgCfI4TwNvwP1QOZPiLP8kx8icN/jvlQIk/TYDPkb/o'
  'TQAAQxNg7E8SAMDIBPgc+4veBAAwMAFG/yQBAIxLgM/Rv+hNAADDEmD8TxIAwKgE+Bz/'
  'i94EADAoAWb4SQIAGJMAnzP8ojcBAAxJgOmcJACA2uf2KgCA8OcmAIDw5/YqAIDw5yYA'
  'gPDn9ioAgPDnJgCA8Of2KgCA8OcmAIDw5/YqAIDw5yYAgPDn9upSAJ8bAAAAAAAAAAAA'
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAP/g+gMJyGwZzsdAAAAABJ'
  'RU5ErkJggg==',
);

/// Runs [body] with all `dart:io` HTTP requests and [NetworkImage] loads
/// intercepted and resolved with [goldenTestNetworkImageStubPng].
///
/// Does nothing when [goldenTestStubNetworkImages] is false.
///
/// Uses [HttpOverrides.global] (not runZoned) so the override is visible inside
/// [WidgetTester.runAsync], which escapes the FakeAsync zone.
Future<T> runWithNetworkImageStub<T>(Future<T> Function() body) async {
  if (!goldenTestStubNetworkImages) return body();

  goldenTestCachedNetworkImageManager?.call();
  final previousOverrides = HttpOverrides.current;
  HttpOverrides.global = _FakeHttpOverrides();
  debugNetworkImageHttpClientProvider = () => _FakeHttpClient();
  try {
    return await body();
  } finally {
    HttpOverrides.global = previousOverrides is _FakeHttpOverrides
        ? null
        : previousOverrides;
    debugNetworkImageHttpClientProvider = null;
  }
}

class _FakeHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) => _FakeHttpClient();
}

class _FakeHttpClient implements HttpClient {
  @override
  bool autoUncompress = true;

  @override
  Duration? connectionTimeout;

  @override
  Duration idleTimeout = const Duration(seconds: 15);

  @override
  int? maxConnectionsPerHost;

  @override
  Future<HttpClientRequest> getUrl(Uri url) async => _FakeHttpClientRequest();

  @override
  Future<HttpClientRequest> get(String host, int port, String path) async =>
      _FakeHttpClientRequest();

  @override
  void close({bool force = false}) {}

  @override
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

class _FakeHttpClientRequest implements HttpClientRequest {
  final _headers = _FakeHttpHeaders();

  @override
  HttpHeaders get headers => _headers;

  @override
  Future<HttpClientResponse> close() async => _FakeHttpClientResponse();

  @override
  Future<HttpClientResponse> get done async => _FakeHttpClientResponse();

  @override
  void add(List<int> data) {}

  @override
  void addError(Object error, [StackTrace? stackTrace]) {}

  @override
  Future<void> addStream(Stream<List<int>> stream) async {
    await stream.drain<void>();
  }

  @override
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

class _FakeHttpHeaders implements HttpHeaders {
  @override
  bool persistentConnection = false;

  @override
  bool chunkedTransferEncoding = false;

  @override
  int contentLength = -1;

  @override
  void set(String name, Object value, {bool preserveHeaderCase = false}) {}

  @override
  void add(String name, Object value, {bool preserveHeaderCase = false}) {}

  @override
  void remove(String name, Object value) {}

  @override
  void removeAll(String name) {}

  @override
  void forEach(void Function(String name, List<String> values) action) {}

  @override
  void noFolding(String name) {}

  @override
  void clear() {}

  @override
  List<String>? operator [](String name) => null;

  @override
  String? value(String name) => null;

  @override
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

/// A no-op [StreamSubscription] returned after synchronous delivery of stub data.
class _CompletedStreamSubscription implements StreamSubscription<List<int>> {
  @override
  bool get isPaused => false;

  @override
  Future<void> cancel() => Future<void>.value();

  @override
  void onData(void Function(List<int> data)? handleData) {}

  @override
  void onError(Function? handleError) {}

  @override
  void onDone(void Function()? handleDone) {}

  @override
  void pause([Future<void>? resumeSignal]) {}

  @override
  void resume() {}

  @override
  Future<E> asFuture<E>([E? futureValue]) => Future<E>.value(futureValue as E);
}

class _FakeHttpClientResponse extends Stream<List<int>>
    implements HttpClientResponse {
  @override
  int get statusCode => HttpStatus.ok;

  @override
  int get contentLength => goldenTestNetworkImageStubPng.length;

  @override
  HttpClientResponseCompressionState get compressionState =>
      HttpClientResponseCompressionState.notCompressed;

  @override
  HttpHeaders get headers => _FakeHttpHeaders();

  @override
  StreamSubscription<List<int>> listen(
    void Function(List<int> event)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) {
    // Deliver data synchronously so consolidateHttpClientResponseBytes
    // collects the bytes in the same microtask, regardless of zone context.
    onData?.call(goldenTestNetworkImageStubPng);
    onDone?.call();
    return _CompletedStreamSubscription();
  }

  @override
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
